#version of docker-compose (3 == latest)
version: '3'
#each services that builds the containers
services:

### Express API ###
  server:
    #path for dockerfiles to use to build the container. it's relative to this docker-compose file
    build: ./dockerize-node    
    #environment variables
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      MONGO_URI: mongodb://mongo/geekclub
    #which port expose to other containers defined in this file. it's declarative, only to give information about which port is exposed
    expose:
      - ${APP_SERVER_PORT}
    #map host machine to container port: host:container
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    #map local source code to the container
    volumes:
      - ./dockerize-node:/usr/src/app
    #command to run after the container is up
    command: node server.js

### React client app ###
  client:
    build: ./dockerize-react
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./dockerize-react:/app
    command: npm run start

### Mongo db
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: geekclub
    #ports:
    #  - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on: 
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example